/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utils;
import services.ServiceProduit;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
//import javax.swing.text.Document;

import com.itextpdf.text.Phrase;
import static com.itextpdf.text.pdf.BidiOrder.PDF;
import static com.itextpdf.text.pdf.PdfName.PDF;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.util.Date;
import static javax.print.DocFlavor.BYTE_ARRAY.PDF;
import static javax.print.DocFlavor.INPUT_STREAM.PDF;
import entites.Produit;

/**
 *
 * @author khadija
 */
public class PDFProduct {
     public void pdfGeneration() throws FileNotFoundException, DocumentException, MalformedURLException, IOException, URISyntaxException {
        Document document = new Document();
        ServiceProduit ps = new ServiceProduit ();
        List<Produit> products= ps.affichageProduit();
       File pdfFile = new File ("produits.pdf");

        PdfWriter.getInstance(document, new FileOutputStream (pdfFile));
        document.open();
        document.addTitle("produits");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Ecocycla");
        document.addCreator("Ecocycla Admin");
        Paragraph preface = new Paragraph();

        Paragraph titre =new Paragraph (" Ecocycla Produits");
        titre.setAlignment (Element.ALIGN_CENTER);

        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + System.getProperty("user.name") + ", " + new Date ()));
        preface.add(new Paragraph(
                "Voici La Liste des Produits "));
        preface.setAlignment (Element.ALIGN_CENTER);
        document.add (titre);
        document.add(preface);
      
        // Start a new page
//        document.newPage();

        PDFProduct pdf=new PDFProduct ();
        PdfPTable table = new PdfPTable(5);

        PdfPCell c1 = new PdfPCell(new Phrase("ID"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Nom"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Description"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Prix"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Stock"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
             

        

       

        table.setHeaderRows(1);
        for (Produit t:products) {
            table.addCell(String.valueOf (t.getId()));
            table.addCell(String.valueOf (t.getNom_p()));
            table.addCell(String.valueOf (t.getDescription_p()));
            table.addCell(String.valueOf (t.getPrix_p()));
            table.addCell(String.valueOf (t.getStock()));
         
           
        }

        document.add (table);
        document.close ();
System.out.println("PDF file location: " + pdfFile.getAbsolutePath());

 }
    
}
